version: "3.7"

services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker123
      - POSTGRES_DB=project
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: project
    restart: always
    ports:
      - 4321:4321
    command: yarn dev
    volumes:
      - .:/usr/app
    links:
      - postgresdb
    depends_on:
      - postgresdb

volumes:
  pgdata:
    driver: local
